import Ember from 'ember';

var dummyGroups = [
	{
	group_id:0,
	name:"Peaceful Puzzle Players",
	desc:"PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN PAIN SUFFERING DESTRUCTION RAISIN-OATMEAL-COOKIES SADNESS SICKNESS PAIN PAIN ",
	leader:0,
	members:[0,1,2,3],
	relatedGames:[1],
	relatedGenres:["PUZZLE","ZEN","SANDBOX","COOKING"],
	posts:[0,1]},
	{
	group_id:1,
	name:"Masochistic Meandering Manslaughterers",
	desc:"HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES HAPPY COOKING CHOCOLATE-CHIP-COOKIES SUGAR PEACE CANDY-SHOPS DELICIOUS-BROWNIES",
	leader:1,
	members:[0,1,2,3],
	relatedGames:[0],
	relatedGenres:["TORTURE SIM","EXISTENTIAL PHILOSOPHICAL","RATED AO","WARGAME SIMULATOR SIMULATOR"],
	posts:[2,3]}
];

export default Ember.Route.extend({
	model: function(params) {
		console.log("group route : "+params.group_id);
		return dummyGroups[params.group_id];
	}
});
